import React, {useEffect, useRef, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Heart, Star, Trophy, Volume2, VolumeX, RotateCcw, ArrowRight, ArrowUp} from 'lucide-react';
import './styles.css';

const W=960,H=460,GROUND=390;
const initial={player:{x:90,y:330,w:28,h:44,vy:0,big:false,face:1}, mushrooms:[{x:355,y:348,w:25,h:22,active:true}], enemies:[{x:520,y:365,w:28,h:25,dir:-1,alive:true},{x:740,y:365,w:28,h:25,dir:1,alive:true}], blocks:[{x:290,y:265,hit:false},{x:330,y:265,hit:false},{x:370,y:265,hit:false,brick:true},{x:410,y:265,hit:false},{x:450,y:265,hit:false}], coins:[{x:350,y:220,got:false},{x:390,y:220,got:false},{x:430,y:220,got:false}], score:0,coinCount:0,lives:3,won:false,dead:false};
function App(){
 const [game,setGame]=useState(initial); const [running,setRunning]=useState(true); const [muted,setMuted]=useState(false); const keys=useRef({}); const raf=useRef();
 const reset=()=>{setGame(JSON.parse(JSON.stringify(initial)));setRunning(true)};
 useEffect(()=>{const down=e=>{keys.current[e.key.toLowerCase()]=true;if(['arrowup','arrowdown','arrowleft','arrowright',' '].includes(e.key.toLowerCase()))e.preventDefault()};const up=e=>keys.current[e.key.toLowerCase()]=false;window.addEventListener('keydown',down);window.addEventListener('keyup',up);return()=>{window.removeEventListener('keydown',down);window.removeEventListener('keyup',up)}},[]);
 useEffect(()=>{if(!running)return;const loop=()=>{setGame(g=>tick(g,keys.current));raf.current=requestAnimationFrame(loop)};raf.current=requestAnimationFrame(loop);return()=>cancelAnimationFrame(raf.current)},[running]);
 const press=k=>{keys.current[k]=true;setTimeout(()=>keys.current[k]=false,140)};
 return <main><header><div className="brand"><div className="pixel-m">M</div><div><div className="eyebrow">NINTENDO-INSPIRED</div><h1>SUPER MARIO</h1></div></div><div className="header-actions"><div className="pill"><span className="online-dot"/> LIVE RUN <b>WORLD 1-1</b></div><button className="icon-btn" onClick={()=>setMuted(!muted)}>{muted?<VolumeX size={19}/>:<Volume2 size={19}/>}</button><button className="icon-btn" onClick={reset}><RotateCcw size={19}/></button></div></header>
 <section className="hero"><div className="hero-copy"><p className="kicker">PIXEL QUEST / 1985</p><h2>THE CLASSIC<br/><em>REIMAGINED.</em></h2><p className="intro">Run, jump, and rescue the Mushroom Kingdom. A tiny tribute to the game that started it all.</p><div className="legend"><span><i className="dot red"/>MOVE</span><span><i className="dot yellow"/>JUMP</span><span><i className="dot blue"/>POWER UP</span></div></div><div className="game-wrap"><div className="game-top"><span>WORLD 1-1</span><span>TIME <b>{String(Math.max(0,Math.floor((game.score?285:300)-(game.score/100)))).padStart(3,'0')}</b></span></div><div className="game" style={{width:W,height:H}}><div className="sky"/><div className="cloud c1"/><div className="cloud c2"/><div className="hill h1"/><div className="hill h2"/><div className="pipe"/><div className="platform p1"/><div className="platform p2"/>{game.blocks.map((b,i)=><div key={i} className={'block '+(b.brick?'brick ':'')+(b.hit?'broken':'')} style={{left:b.x,top:b.y}}>{!b.brick&&!b.hit&&'?'}</div>)}{game.coins.map((c,i)=>!c.got&&<div key={i} className="coin" style={{left:c.x,top:c.y}}>¢</div>)}{game.mushrooms.map((m,i)=>m.active&&<div key={i} className="mushroom" style={{left:m.x,top:m.y}}><span/></div>)}{game.enemies.map((e,i)=>e.alive&&<div key={i} className="goomba" style={{left:e.x,top:e.y}}><div className="eyes">◉ ◉</div></div>)}<div className={'player '+(game.player.big?'big':'')} style={{left:game.player.x,top:game.player.y,transform:`scaleX(${game.player.face})`}}><div className="cap"/><div className="head"/><div className="body"/><div className="boots"/></div><div className="ground"/>{game.dead&&<div className="overlay"><strong>GAME OVER</strong><button onClick={reset}>TRY AGAIN</button></div>}{game.won&&<div className="overlay"><strong>LEVEL CLEAR!</strong><button onClick={reset}>PLAY AGAIN</button></div>}</div><div className="game-hint"><span><b>← →</b> RUN</span><span><b>SPACE</b> JUMP</span><span><b>★</b> GET BIG</span></div></div></section>
 <section className="stats"><div className="stat main-stat"><span className="stat-label">SCORE</span><strong>{String(game.score).padStart(6,'0')}</strong><small>BEST 001280</small></div><div className="stat"><span className="stat-label">COINS</span><strong className="gold">× {game.coinCount}</strong><small><Star size={13} fill="currentColor"/> KEEP COLLECTING</small></div><div className="stat"><span className="stat-label">LIVES</span><strong className="lives">{[0,1,2].map(i=><Heart key={i} size={19} fill={i<game.lives?'currentColor':'none'}/>)}</strong><small>CHANCES LEFT</small></div><div className="stat goal"><span className="stat-label">MISSION</span><strong><Trophy size={18}/> REACH THE FLAG</strong><small>{game.player.big?'POWERED UP':'FIND A MUSHROOM'}</small></div></section>
 <footer><span>© 2024 PIXEL QUEST ARCADE</span><span>BUILT WITH <b>♥</b> FOR THE MUSHROOM KINGDOM</span><span>INSERT COIN <ArrowRight size={14}/></span></footer>
 <div className="mobile-controls"><button onPointerDown={()=>press('arrowleft')}>←</button><button onPointerDown={()=>press(' ')}><ArrowUp/></button><button onPointerDown={()=>press('arrowright')}>→</button></div></main>
}
function tick(g,k){if(g.dead||g.won)return g;let n=JSON.parse(JSON.stringify(g)),p=n.player;let left=k['arrowleft']||k['a'],right=k['arrowright']||k['d']; if(left){p.x-=3.5;p.face=-1}if(right){p.x+=3.5;p.face=1}p.x=Math.max(12,Math.min(W-45,p.x));if((k[' ']||k['arrowup']||k['w'])&&p.y>=GROUND-p.h-1)p.vy=-10; p.vy+=.45;p.y+=p.vy;if(p.y>GROUND-p.h){p.y=GROUND-p.h;p.vy=0}
 n.enemies.forEach(e=>{if(!e.alive)return;e.x+=e.dir*1.15;if(e.x<450||e.x>875)e.dir*=-1; if(overlap(p,e)){if(p.vy>1&&p.y+p.h<e.y+14){e.alive=false;p.vy=-7;n.score+=100}else{n.lives--;if(n.lives<=0)n.dead=true;p.x=90;p.y=330;p.vy=0}}});n.mushrooms.forEach(m=>{if(m.active&&overlap(p,m)){m.active=false;p.big=true;n.score+=1000}});n.coins.forEach(c=>{if(!c.got&&overlap(p,{x:c.x,y:c.y,w:20,h:25})){c.got=true;n.coinCount++;n.score+=200}});n.blocks.forEach(b=>{if(!b.hit&&p.vy<0&&p.y<=b.y+32&&p.y>=b.y-16&&p.x+p.w>b.x&&p.x<b.x+32){if(p.big&&b.brick){b.hit=true;n.score+=50}else if(!b.brick){b.hit=true;n.score+=100}}});if(p.x>900)n.won=true;return n}
function overlap(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y}
createRoot(document.getElementById('root')).render(<App/>);
