'use strict';
/* ============================================================
 * 像素精灵：用 ASCII 画布 + 调色板生成 canvas，全部运行时绘制
 * 16x16 / 16x32 像素，与 NES 原版近似
 * ============================================================ */
const SPRITE_PAL = {
  K:'#000000', W:'#fcfcfc', R:'#e52521', r:'#a01020', H:'#6a2c00',
  S:'#fcb578', B:'#2038ec', b:'#5c5cf0', Y:'#f8d800', N:'#8c4000',
  C:'#f8d878', G:'#00a800', g:'#007800', O:'#d86838', D:'#9c4a10',
  P:'#f83800', T:'#f8f800', M:'#c8c8c8', E:'#e8a050', Z:'#58a0f8'
};

const ART = {
  /* ---------- 小马力欧 16x16 ---------- */
  smallStand: [
    '................',
    '................',
    '.....KKKK.......',
    '....RRRRRR......',
    '....RRRRRRR.....',
    '...RRRRRRRR.....',
    '...HHHHHHHH.....',
    '..HHHHHHHHHH....',
    '..SSSSSSSSSS....',
    '..SSSSSSSKSS....',
    '..SSSSSSSSSS....',
    '..RRRRRRRRRR....',
    '.RRRRRRRRRRRR...',
    '.BBBBBBBBBBBB...',
    '.BBBB..BBBBB....',
    '.NNNN..NNNNN....',
  ],
  smallWalk1: [
    '................',
    '................',
    '.....KKKK.......',
    '....RRRRRR......',
    '....RRRRRRR.....',
    '...RRRRRRRR.....',
    '...HHHHHHHH.....',
    '..HHHHHHHHHH....',
    '..SSSSSSSKSS....',
    '..SSSSSSSSSS....',
    '..SSSSSSSSSS....',
    '..RRRRRRRRRR....',
    '.RRRRRRRRRRRR...',
    '.BBBBBBBBBBBS...',
    '.BBBB..BBBBB....',
    'NNNNN..NNNNN....',
  ],
  smallWalk2: [
    '................',
    '................',
    '.....KKKK.......',
    '....RRRRRR......',
    '....RRRRRRR.....',
    '...RRRRRRRR.....',
    '...HHHHHHHH.....',
    '..HHHHHHHHHH....',
    '..SSSSSSSKSS....',
    '..SSSSSSSSSS....',
    '..SSSSSSSSSS....',
    '..RRRRRRRRRR....',
    '.RRRRRRRRRRRR...',
    '.BBBBBBBBBBBBS..',
    '.BBBB..BBBBB....',
    '.NNNN..NNNNN....',
  ],
  smallJump: [
    '................',
    '................',
    '.....KKKK.......',
    '....RRRRRR......',
    '....RRRRRRR.....',
    '...RRRRRRRR.....',
    '...HHHHHHHH.....',
    '..HHHHHHHHHH....',
    '..SSSSSSSKSS....',
    '..SSSSSSSSSS....',
    '..SSSSSSSSSS....',
    '..RRRRRRRRRR....',
    '.RRRRRRRRRRRR...',
    '..BBBBBBBBBB....',
    '..BBBB..BBBB....',
    '..NNNN..NNNN....',
  ],
  smallSkid: [
    '................',
    '................',
    '.....KKKK.......',
    '....RRRRRR......',
    '....RRRRRRR.....',
    '...RRRRRRRR.....',
    '...HHHHHHHH.....',
    '..HHHHHHHHHH....',
    '..SSSSSSSKSS....',
    '..SSSSSSSSSS....',
    '..SSSSSSSSSS....',
    '..RRRRRRRRRR....',
    '.RRRRRRRRRRRR...',
    '.BBBBBBBBBBBBS..',
    '.BBBB.BBBBBB....',
    '.NNNN..NNNNN....',
  ],
  smallDead: [
    '................',
    '................',
    '.....KKKK.......',
    '....RRRRRR......',
    '....RRRRRRR.....',
    '...RRRRRRRR.....',
    '...HHHHHHHH.....',
    '..HHHHHHHHHH....',
    '..SSSSSSSKSS....',
    '..KSSSSSSSSK....',
    '..SSSSSSSSSS....',
    '..RRRRRRRRRR....',
    '.RRRRRRRRRRRR...',
    '.BBBBBBBBBBBB...',
    '.BBBB..BBBBB....',
    '.NNNN..NNNNN....',
  ],

  /* ---------- 大马力欧 16x32（火球形态通过调色板替换） ---------- */
  bigStand: [
    '................',
    '................',
    '.....KKKK.......',
    '....RRRRRR......',
    '....RRRRRRR.....',
    '...RRRRRRRR.....',
    '...RRRRRRRR.....',
    '..RRRRRRRRRR....',
    '..HHHHHHHHHH....',
    '..HHHHHHHHHH....',
    '..SSSSSSSSSS....',
    '..SSSSSSSSSS....',
    '..SSSSSSSSSS....',
    '..SSSSSSSSSS....',
    '..SSSSSSSSSS....',
    '..WWWWWWWWWW....',
    '.WWWWWWWWWWWW...',
    '.WWWWWWWWWWWW...',
    '.WWWWWWWWWWWW...',
    '.WWWWWWWWWWWW...',
    '..RRRRRRRRRR....',
    '..RRRRRRRRRR....',
    '..RRRRRRRRRR....',
    '.S.RRRRRRRR.S...',
    '.S.RRRRRRRR.S...',
    '..RRRR..RRRR....',
    '..RRRR..RRRR....',
    '..RRRR..RRRR....',
    '..RRRR..RRRR....',
    '.NNNNN..NNNNN...',
    '.NNNNNN.NNNNN...',
    '.NNNNNN.NNNNN...',
  ],
  bigWalk1: [
    '................',
    '................',
    '.....KKKK.......',
    '....RRRRRR......',
    '....RRRRRRR.....',
    '...RRRRRRRR.....',
    '...RRRRRRRR.....',
    '..RRRRRRRRRR....',
    '..HHHHHHHHHH....',
    '..HHHHHHHHHH....',
    '..SSSSSSSSSS....',
    '..SSSSSSSSSS....',
    '..SSSSSSSSSS....',
    '..SSSSSSSSSS....',
    '..SSSSSSSSSS....',
    '..WWWWWWWWWW....',
    '.WWWWWWWWWWWW...',
    '.WWWWWWWWWWWW...',
    '.WWWWWWWWWWWW...',
    '.WWWWWWWWWWWW...',
    '..RRRRRRRRRR....',
    '..RRRRRRRRRR....',
    '.S.RRRRRRRR.S...',
    '.S.RRRRRRRR.S...',
    '..RRRR..RRRR....',
    '..RRRR..RRRR....',
    '..RRRR..RRRR....',
    '..RRRR..RRRR....',
    '.NNNN...NNNNN...',
    '.NNNNN...NNNN...',
    '.NNNNNN..NNNN...',
    '................',
  ],
  bigWalk2: [
    '................',
    '................',
    '.....KKKK.......',
    '....RRRRRR......',
    '....RRRRRRR.....',
    '...RRRRRRRR.....',
    '...RRRRRRRR.....',
    '..RRRRRRRRRR....',
    '..HHHHHHHHHH....',
    '..HHHHHHHHHH....',
    '..SSSSSSSSSS....',
    '..SSSSSSSSSS....',
    '..SSSSSSSSSS....',
    '..SSSSSSSSSS....',
    '..SSSSSSSSSS....',
    '..WWWWWWWWWW....',
    '.WWWWWWWWWWWW...',
    '.WWWWWWWWWWWW...',
    '.WWWWWWWWWWWW...',
    '.WWWWWWWWWWWW...',
    '..RRRRRRRRRR....',
    '..RRRRRRRRRR....',
    '.S.RRRRRRRR.S...',
    '.S.RRRRRRRR.S...',
    '..RRRR..RRRR....',
    '..RRRR..RRRR....',
    '..RRRR..RRRR....',
    '..RRRR..RRRR....',
    '..NNNN..NNNN....',
    '.NNNNN..NNNNN...',
    '.NNNNN..NNNNN...',
    '................',
  ],
  bigJump: [
    '................',
    '................',
    '.....KKKK.......',
    '....RRRRRR......',
    '....RRRRRRR.....',
    '...RRRRRRRR.....',
    '...RRRRRRRR.....',
    '..RRRRRRRRRR....',
    '..HHHHHHHHHH....',
    '..HHHHHHHHHH....',
    '..SSSSSSSSSS....',
    '..SSSSSSSSSS....',
    '..SSSSSSSSSS....',
    '..SSSSSSSSSS....',
    '..SSSSSSSSSS....',
    '..WWWWWWWWWW....',
    '.WWWWWWWWWWWW...',
    '.WWWWWWWWWWWW...',
    'S.WWWWWWWWWW....',
    'SS.WWWWWWWWW....',
    '..RRRRRRRRRR....',
    '..RRRRRRRRRR....',
    '..RRRRRRRRRR....',
    '..RRRRRRRRRR....',
    '..RRRR..RRRR....',
    '..RRRR..RRRR....',
    '..NNNN..NNNN....',
    '..NNNN..NNNN....',
    '................',
    '................',
    '................',
    '................',
  ],
  bigSkid: [
    '................',
    '................',
    '.....KKKK.......',
    '....RRRRRR......',
    '....RRRRRRR.....',
    '...RRRRRRRR.....',
    '...RRRRRRRR.....',
    '..RRRRRRRRRR....',
    '..HHHHHHHHHH....',
    '..HHHHHHHHHH....',
    '..SSSSSSSSSS....',
    '..SSSSSSSSSS....',
    '..SSSSSSSSSS....',
    '..SSSSSSSSSS....',
    '..SSSSSSSSSS....',
    '..WWWWWWWWWW....',
    '.WWWWWWWWWWWW...',
    '.WWWWWWWWWWWW...',
    'S.WWWWWWWWWWW...',
    '.WWWWWWWWWWWW...',
    '..RRRRRRRRRR....',
    '..RRRRRRRRRR....',
    '.S.RRRRRRRR.S...',
    '.S.RRRRRRRR.S...',
    '..RRRR..RRRR....',
    '..RRRR..RRRR....',
    '.NNNN....NNNN...',
    '.NNNNN...NNNNN..',
    '.NNNNNN..NNNNN..',
    '................',
    '................',
    '................',
  ],

  /* ---------- 板栗仔 Goomba ---------- */
  goomba1: [
    '................',
    '................',
    '....KKKKKKKK....',
    '..KKKKKKKKKKKK..',
    '.KKKKKKKKKKKKKK.',
    '.KDDDDDDDDDDDDK.',
    'KDDWWKDDDDKWWDDK',
    'KDDWWKDDDDKWWDDK',
    'KDDDDKKKKKKDDDDK',
    'KDDDDKKKKKKDDDDK',
    '.KDDDDDDDDDDDDK.',
    '.KKKDDDDDDDDKKK.',
    '..KKDDDDDDDDKK..',
    '..KDDDD..KDDDD..',
    '.KDDDDK..KDDDDK.',
    '................',
  ],
  goomba2: [
    '................',
    '................',
    '....KKKKKKKK....',
    '..KKKKKKKKKKKK..',
    '.KKKKKKKKKKKKKK.',
    '.KDDDDDDDDDDDDK.',
    'KDDWWKDDDDKWWDDK',
    'KDDWWKDDDDKWWDDK',
    'KDDDDKKKKKKDDDDK',
    'KDDDDKKKKKKDDDDK',
    '.KDDDDDDDDDDDDK.',
    '.KKKDDDDDDDDKKK.',
    '..KKDDDDDDDDKK..',
    '..KDDDD..KDDDD..',
    '..KDDDD..KDDDD..',
    '................',
  ],
  goombaSquash: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '.KKKKKKKKKKKKKK.',
    'KDDDDDDDDDDDDDDK',
    '.KDDDD..KDDDDK..',
    '................',
  ],

  /* ---------- 乌龟 Koopa ---------- */
  koopa1: [
    '................',
    '....KKKKKKKK....',
    '..KKGGGGGGGGKK..',
    '.KGGGGGGGGGGGGK.',
    '.KGGGGGGGGGGGGK.',
    'KGGGGGGGGGGGGGGK',
    'KGGgGGGGGGGGgGGK',
    'KGGgGGGGGGGGgGGK',
    '.KGGGGGGGGGGGGK.',
    '.KKGGGGGGGGGGKK.',
    '..KKKKKKKKKKKK..',
    '....KKKKKKKK....',
    '................',
    '..KKKKKKKKKKKK..',
    '.KKKSSSSSSSSKKK.',
    '.KSSSSSSSSSSSSK.',
    'KSSKSSSSSSSKSSSK',
    'KSSKSSSSSSSKSSSK',
    'KSSSSSSSSSSSSSSK',
    '.KSSSSSSSSSSSSK.',
    '..KKKKKKKKKKKK..',
    '..KSSS..KSSS....',
    '.KSSSKK..KSSSKK.',
    '................',
  ],
  koopa2: [
    '................',
    '....KKKKKKKK....',
    '..KKGGGGGGGGKK..',
    '.KGGGGGGGGGGGGK.',
    '.KGGGGGGGGGGGGK.',
    'KGGGGGGGGGGGGGGK',
    'KGGgGGGGGGGGgGGK',
    'KGGgGGGGGGGGgGGK',
    '.KGGGGGGGGGGGGK.',
    '.KKGGGGGGGGGGKK.',
    '..KKKKKKKKKKKK..',
    '....KKKKKKKK....',
    '................',
    '..KKKKKKKKKKKK..',
    '.KKKSSSSSSSSKKK.',
    '.KSSSSSSSSSSSSK.',
    'KSSKSSSSSSSKSSSK',
    'KSSKSSSSSSSKSSSK',
    'KSSSSSSSSSSSSSSK',
    '.KSSSSSSSSSSSSK.',
    '..KKKKKKKKKKKK..',
    '..KSSS..KSSS....',
    '..KSSSK.KSSSK...',
    '................',
  ],
  shell: [
    '................',
    '....KKKKKKKK....',
    '..KKGGGGGGGGKK..',
    '.KGGGGGGGGGGGGK.',
    '.KGGGGGGGGGGGGK.',
    'KGGGGGGGGGGGGGGK',
    'KGGgGGGGGGGGgGGK',
    'KGGgGGGGGGGGgGGK',
    '.KGGGGGGGGGGGGK.',
    '.KKGGGGGGGGGGKK.',
    '..KKKKKKKKKKKK..',
    '................',
  ],

  /* ---------- 蘑菇 / 1UP / 花 / 星星 ---------- */
  mushroom: [
    '................',
    '....KKKKKKKK....',
    '..KKRRRRRRRRKK..',
    '.KRRRRRRRRRRRRK.',
    '.KRWRRRRRRRRWRK.',
    '.KRWRRRRRRRRWRK.',
    '.KRRRRRRRRRRRRK.',
    '..KKKKKKKKKKKK..',
    '...KCCCCCCCCK...',
    '..KCCKKCCKKCCK..',
    '..KCCCCCCCCCCK..',
    '..KCCCCCCCCCCK..',
    '..KCCCCCCCCCCK..',
    '..KKKKKKKKKKKK..',
    '................',
    '................',
  ],
  flower: [
    '................',
    '....KKKKKKKK....',
    '..KKPPPPPPPPKK..',
    '.KPPPPPKKPPPPPKK',
    '.KPPKKPPPPKKPPK.',
    '.KPPKKPPPPKKPPK.',
    '.KPPPPPPPPPPPPK.',
    '..KKKKKKKKKKKK..',
    '....KGGGGGGK....',
    '....KGGGGGGK....',
    '..KKKGGGGGGKKK..',
    '.KGGGGKKKKGGGGK.',
    '.KGGGGKKKKGGGGK.',
    '..KKKKKKKKKKKK..',
    '................',
    '................',
  ],
  star1: [
    '................',
    '.....KKKKK......',
    '...KKYYYYYKK....',
    '..KYYYYYYYYYK...',
    '.KYYYYYYYYYYYK..',
    '.KYKKYYYYYYKKYK.',
    '.KYYYYYYYYYYYYK.',
    '.KYKKYYYYYYKKYK.',
    '..KYYYYYYYYYK...',
    '...KKYYYYYKK....',
    '.....KKKKK......',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
  star2: [
    '................',
    '.....KKKKK......',
    '...KKYYYYYKK....',
    '..KYYYYYYYYYK...',
    '.KYYYYYYYYYYYK..',
    '.KYYYYYYYYYYKYK.',
    '.KYYYYYYYYYYYYK.',
    '.KYKYYYYYYYYYKY.',
    '..KYYYYYYYYYK...',
    '...KKYYYYYKK....',
    '.....KKKKK......',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],

  /* ---------- 问号砖 / 用过砖 ---------- */
  blockQ: [
    'KKKKKKKKKKKKKKKK',
    'KYYYYYYYYYYYYYYK',
    'KYYYYYYYYYYYYYYK',
    'KYYYYYYYYYYYYYYK',
    'KYYYYYKKKKYYYYYK',
    'KYYYYYKKKKYYYYYK',
    'KYYYYYYYKKYYYYYK',
    'KYYYYYYYKKYYYYYK',
    'KYYYYYYYYYYYYYYK',
    'KYYYYYYYYYYYYYYK',
    'KYYYYYYKKYYYYYYK',
    'KYYYYYYYYYYYYYYK',
    'KYYYYYYYYYYYYYYK',
    'KYYYYYYYYYYYYYYK',
    'KYYYYYYYYYYYYYYK',
    'KKKKKKKKKKKKKKKK',
  ],
  blockUsed: [
    'KKKKKKKKKKKKKKKK',
    'KDDDDDDDDDDDDDDK',
    'KDDDDDDDDDDDDDDK',
    'KDDDDDDDDDDDDDDK',
    'KDDDDDDDDDDDDDDK',
    'KDDDDDDDDDDDDDDK',
    'KDDDDDDDDDDDDDDK',
    'KDDDDDDDDDDDDDDK',
    'KDDDDDDDDDDDDDDK',
    'KDDDDDDDDDDDDDDK',
    'KDDDDDDDDDDDDDDK',
    'KDDDDDDDDDDDDDDK',
    'KDDDDDDDDDDDDDDK',
    'KDDDDDDDDDDDDDDK',
    'KDDDDDDDDDDDDDDK',
    'KKKKKKKKKKKKKKKK',
  ],
};

/* ---------- 构建缓存 ---------- */
const SPRITES = {};
function buildSprite(lines, remap) {
  const h = lines.length, w = lines[0].length;
  const cv = document.createElement('canvas');
  cv.width = w; cv.height = h;
  const ctx = cv.getContext('2d');
  for (let r = 0; r < h; r++) {
    const line = lines[r];
    for (let c = 0; c < w; c++) {
      let ch = line[c];
      if (remap && remap[ch]) ch = remap[ch];
      const col = SPRITE_PAL[ch];
      if (!col) continue;
      ctx.fillStyle = col;
      ctx.fillRect(c, r, 1, 1);
    }
  }
  return cv;
}

function ensureSprites() {
  if (SPRITES.built || !document) return;
  SPRITES.built = true;
  const fireRemap = { R:'W', W:'R' };
  SPRITES.smallStand = buildSprite(ART.smallStand);
  SPRITES.smallWalk1 = buildSprite(ART.smallWalk1);
  SPRITES.smallWalk2 = buildSprite(ART.smallWalk2);
  SPRITES.smallJump = buildSprite(ART.smallJump);
  SPRITES.smallSkid = buildSprite(ART.smallSkid);
  SPRITES.smallDead = buildSprite(ART.smallDead);
  SPRITES.bigStand = buildSprite(ART.bigStand);
  SPRITES.bigWalk1 = buildSprite(ART.bigWalk1);
  SPRITES.bigWalk2 = buildSprite(ART.bigWalk2);
  SPRITES.bigJump = buildSprite(ART.bigJump);
  SPRITES.bigSkid = buildSprite(ART.bigSkid);
  SPRITES.bigFire = {};
  SPRITES.bigFire.stand = buildSprite(ART.bigStand, fireRemap);
  SPRITES.bigFire.walk1 = buildSprite(ART.bigWalk1, fireRemap);
  SPRITES.bigFire.walk2 = buildSprite(ART.bigWalk2, fireRemap);
  SPRITES.bigFire.jump = buildSprite(ART.bigJump, fireRemap);
  SPRITES.bigFire.skid = buildSprite(ART.bigSkid, fireRemap);
  SPRITES.goomba1 = buildSprite(ART.goomba1);
  SPRITES.goomba2 = buildSprite(ART.goomba2);
  SPRITES.goombaSquash = buildSprite(ART.goombaSquash);
  SPRITES.koopa1 = buildSprite(ART.koopa1);
  SPRITES.koopa2 = buildSprite(ART.koopa2);
  SPRITES.shell = buildSprite(ART.shell);
  SPRITES.mushroom = buildSprite(ART.mushroom);
  SPRITES.mushroom1up = buildSprite(ART.mushroom, { R:'G' });
  SPRITES.flower = buildSprite(ART.flower);
  SPRITES.star1 = buildSprite(ART.star1);
  SPRITES.star2 = buildSprite(ART.star2);
  SPRITES.blockQ = buildSprite(ART.blockQ);
  SPRITES.blockUsed = buildSprite(ART.blockUsed);
}

/* 带翻转地绘制精灵：sx, sy 为精灵左上角 */
function drawSprite(ctx, spr, x, y, flip) {
  if (!spr) return;
  if (flip) {
    ctx.save();
    ctx.translate(x + spr.width, y);
    ctx.scale(-1, 1);
    ctx.drawImage(spr, 0, 0);
    ctx.restore();
  } else {
    ctx.drawImage(spr, x, y);
  }
}
